### ISSUE TITLE
Add X-CDP-SDK header to all requests

### ISSUE THREAD

**Issue by ghost** [cognitedata/cognite-sdk-js#102]

**Comment by ghost** [comment]
Same format as this one: https://github.com/cognitedata/cognite-sdk-python/blob/v1.0.0/cognite/client/_api_client.py#L144

**Comment by polomani** [comment]
https://github.com/cognitedata/cognitesdk-js/pull/103

**Comment by polomani** [comment]
I believe we could start using this syntax for commits https://help.github.com/en/articles/closing-issues-using-keywords @f1cognite
