### ISSUE TITLE
Make it easy to traverse/retrieve a subtree

### ISSUE THREAD

**Issue by ghost** [cognitedata/cognite-sdk-js#121]
Similar to the one in the Python SDK: https://cognite-docs.readthedocs-hosted.com/projects/cognite-sdk-python/en/latest/cognite.html#retrieve-an-asset-subtree

**Comment by ghost** [comment]
Will be solved by issue #129

**Comment by polomani** [comment]
Moved to Jira https://cognitedata.atlassian.net/browse/DEVX-18?atlOrigin=eyJpIjoiNjkyZjY5MzkzMzc5NGQ2Nzk1NmNlY2MwMjUxNjg5ZGUiLCJwIjoiaiJ9
