### ISSUE TITLE
Improve documentation page

### ISSUE THREAD

**Issue by ghost** [cognitedata/cognite-sdk-js#136]
- Can we sort the order of the sections on the main page?
  - Classes
  - Functions
- Can we hide interfaces/types from main page?
- Specify git-commit for consistent lookup of files
- Include the README-file?
- Track usage of the page (GA)?

**Comment by polomani** [comment]
Moved to Jira https://cognitedata.atlassian.net/browse/DEVX-19?atlOrigin=eyJpIjoiZGYyZGQ0Y2YzNjlhNDAxMjk4OTFjNmJmZmVhOGUxMGQiLCJwIjoiaiJ9
