### ISSUE TITLE
Enhancement: SDK Examples should not use boilerplate templates

### ISSUE THREAD

**Issue by evenstensberg** [cognitedata/cognite-sdk-js#164]
It would be nice if we had the examples that are ejected by create react app manually made, such that it is as simple, clean and has an appropriate README.

**Comment by ghost** [comment]
I din't think this is the case for SDK v1: https://github.com/cognitedata/cognitesdk-js/tree/v1 that will very (!) soon be the default branch

**Comment by polomani** [comment]
The issue is only for 0.5. Please update to v1
