### ISSUE TITLE
Expose types properly

### ISSUE THREAD

**Issue by polomani** [cognitedata/cognite-sdk-js#167]

**Comment by ghost** [comment]
The problem here is that the types `Asset`, `ExternalAssetItem` etc is not easily accessible from our SDK.

**Comment by polomani** [comment]
most likely we need to do `export * from './types/types'`

**Comment by ghost** [comment]
If we do this then all all types will be exported on the top-level... Is that what we want?

**Comment by ghost** [comment]
What is the problem with:
```js
import { types } from '@cognite/sdk';
const asset: types.Asset = {...};
```
?

**Comment by polomani** [comment]
If you hit control-space vscode automatically import like this
`import { ... } from '@cognite/sdk/dist/src/types/types';`
Not the way you mentioned above.
That makes development annoying, as you need to remember to type only `types.something` every time.
Also you can't do destructive import.. so you will have a lot of 
`thing1: types.thisThing` and `thing2: types.thatThing` which looks unprofessionally.

**Comment by ghost** [comment]
We need to land this. Should we do `export * from './types/types'` then?

**Comment by polomani** [comment]
@f1cognite I believe we need to do so, yes
