### ISSUE TITLE
Enhancement: SDK documentation with example code

### ISSUE THREAD

**Issue by evenstensberg** [cognitedata/cognite-sdk-js#187]
## Problem

As an initial user of the SDK, some examples inlined in the SDK documentation would be great. This way, a developer is less confused by looking at the types written in TypeScript. Most of the time, having these examples written in plain JavaScript reduces the overhead we put on the initial user and the baseline for having people trying out the API is lesser than having the documentation is TypeScript.

# Proposed 
Striking a middleground between having the types and parameters in TypeScript and examples in JavaScript would be nice

**Comment by ghost** [comment]
@evenstensberg have you checked out [this folder](https://github.com/cognitedata/cognitesdk-js/tree/v1/samples) and the code snippets we have in the [v1-reference documentation](https://doc.cognitedata.com/api/v1/)?

In the SDK reference documentation for SDK (api v1) we have code snippets for all api-calls: https://cognitedata.github.io/cognitesdk-js/classes/assetmappings3dapi.html#create

**Comment by evenstensberg** [comment]
This is issue is mostly scoped towards the last link you sent. Was using v.0.5, v1 docs and samples looks really nice, it would be awesome to have the same for v0.5 if supporting that for some time in the future. If going to be depreciated, feel free to close the issue!
