### ISSUE TITLE
Update code snippets in Cognite OpenAPI spec when releasing v1

### ISSUE THREAD

**Issue by ghost** [cognitedata/cognite-sdk-js#201]
Hopefully we can automate this procedure.

**Comment by polomani** [comment]
basically this does it https://github.com/cognitedata/cognitesdk-js/pull/223
`scripts/afterRelease.sh` generates it and make a pr to service contracts and it works perfectly locally
although I wasn't succeed in doing it with travis.
It seems that `hub` has some issues connecting with github_token

**Comment by eirikdahlen** [comment]
Moved to [JIRA](https://cognitedata.atlassian.net/secure/RapidBoard.jspa?rapidView=55&projectKey=DEVX&modal=detail&selectedIssue=DEVX-12)
