### ISSUE TITLE
Fix security vulnerabilities

### ISSUE THREAD

**Issue by ghost** [cognitedata/cognite-sdk-js#228]
Can find them by running `yarn audit` or go here: https://github.com/cognitedata/cognitesdk-js/network/alerts

**Comment by polomani** [comment]
fixed some of them https://github.com/cognitedata/cognitesdk-js/pull/233
but not everything, explained in pr

**Comment by eirikdahlen** [comment]
Moved to [JIRA](https://cognitedata.atlassian.net/secure/RapidBoard.jspa?rapidView=55&projectKey=DEVX&modal=detail&selectedIssue=DEVX-12)

**Comment by eirikdahlen** [comment]
Moved to [JIRA](https://cognitedata.atlassian.net/secure/RapidBoard.jspa?rapidView=55&projectKey=DEVX&modal=detail&selectedIssue=DEVX-16)
