### ISSUE TITLE
Update Asset interface with new rootId option and document it

### ISSUE THREAD

**Issue by khalzmax** [cognitedata/cognite-sdk-js#236]
According to the data fetched from the new Cognite API _Asset_ has got new field **rootId**. However it is not documented and does not exist in the [Asset](https://cognitedata.github.io/cognitesdk-js/interfaces/asset.html) interface. 
It seems to be the only way to recognize root assets in SDK 2.0

**Comment by ghost** [comment]
Moved ticket to: https://cognitedata.atlassian.net/browse/DEVX-21?atlOrigin=eyJpIjoiMTA3Y2FmNzNiOWUxNGJhNzkxYTEwNjk4NWQwYmRkNGQiLCJwIjoiaiJ9
