### ISSUE TITLE
The type AclScopeTimeseries is divergent with the API docs

### ISSUE THREAD

**Issue by nildo** [cognitedata/cognite-sdk-js#316]
The type `AclScopeTimeseries` is currently defined as `AclScopeAll | AclScopeAssetsId`.

Today you can't use `AclScopeAssetsId` in groups creation anymore.

It is also missing the option of a `TimeSeriesIdScope`, according to the API v1 docs (https://docs.cognite.com/api/v1/#operation/createGroups).

Then, when using TypeScript, there is a typing error when assigning a group scoped by time series ids to a variable of type Group.

**Comment by polomani** [comment]
hmm, it seems like documentation is not in sync with protobufs again
https://github.com/cognitedata/api-acls/blob/a85c3f37f4b9893ddb2dde6a59416a9b37e9ffe0/protos/timeseries_acl.proto

@ngerstle-cognite  could you confirm that `assetIdScope.subtreeIds` still exists?

and now also `assetIds` has been added?

**Comment by ngerstle-cognite** [comment]
Subtree IDs exist, but can't be created anymore.

**Comment by nildo** [comment]
Since the subtree IDs still exist, and just can't be created anymore, I think the PR #317 fixes the whole problem. timeseries ids exists and can be created, so, they just need to be added there.
