### ISSUE TITLE
Failed to minify the code

### ISSUE THREAD

**Issue by valgussev** [cognitedata/cognite-sdk-js#33]
In this commit https://github.com/cognitedata/cognitesdk-js/commit/9d397360297dbc98d5ee44dcc4fa4b4ce2ce7e75 `retry-axios` has been introduced  (v1.4.2) which in compiled version contains not transpiled es6 code, which leads to the following error in create-react-app build process:
```
Failed to minify the code from this file: 
 	./node_modules/@cognite/sdk/node_modules/retry-axios/build/src/index.js:67 
Read more here: http://bit.ly/2tRViJ9

```
Explanation could be found here https://facebook.github.io/create-react-app/docs/troubleshooting#npm-run-build-fails-to-minify. All applications which are using older version of cra will fail to build.

**Comment by ghost** [comment]
I have created a pull request here: https://github.com/JustinBeckwith/retry-axios/pull/38
and I have reported to `es-check` that our es5-test (`yarn esCheck`) didn't find the issue: https://github.com/dollarshaveclub/es-check/issues/90
