### ISSUE TITLE
Authentication in production

### ISSUE THREAD

**Issue by hasithajayasundara** [cognitedata/cognite-sdk-js#332]
I've tested the following using a create-react-app project.

```
import React, { Component } from "react";
import { CogniteClient } from "@cognite/sdk";
import { ClientSDKProvider } from "@cognite/gearbox";
import "antd/dist/antd.css";

const APP_ID = "hello-cdf-gearboxjs";
const PROJECT_ID = "publicdata";

class App extends Component {
  
state = {
       client:null
  };

 async componentDidMount() {
    const client = new CogniteClient({
      appId: APP_ID
    });
    client.loginWithOAuth({ project: PROJECT_ID });
    await client.authenticate();
    this.setState({ client });
  }

  render() {
    return (
      <div>
        {this.state.client && (
          <ClientSDKProvider client={this.state.client}>
          </ClientSDKProvider>
        )}

        {!this.state.client && <div>Please wait ...</div>}
      </div>
    );
  }
}

export default App;
```
**This works fine in a local setup. (When run using create-react-app server)**

I've also tried to deploy this in Heroku as a production version and I'm getting following error.

```
{
  "error": {
    "code": 400,
    "message": "Invalid redirect url"
  }
}
```
Any thoughts on resolving this? (Posted here as I suspect that the issue generates from client.loginWithOAuth() method call).

**Comment by nalaka** [comment]
The redirect URL (in your external host) needs to be  provisioned under the relevent tenant- `publicdata` in this case, for this to work. There is an exception for `localhost`- that's why it works when you run locally.

**Comment by hasithajayasundara** [comment]
@nalaka thanks for the response.
