### ISSUE TITLE
Cookie without "sameSite" attribute.

### ISSUE THREAD

**Issue by annitya** [cognitedata/cognite-sdk-js#364]
![image](https://user-images.githubusercontent.com/727305/78809367-18380a00-79c7-11ea-977c-f00ed2c12e3f.png)

Chrome is whining. You fix? :)

**Comment by hhenriques** [comment]
Hey @annitya sorry for getting back to you so late. We'll look into it

**Comment by annitya** [comment]
Can't reproduce. Consider it fixed :)

**Comment by annitya** [comment]
Nevermind, it came back. A somewhat elusive one it would seem.

**Comment by haved** [comment]
This seems to be reproducible on all insight.cogniteapp.com sites if opened in a new private browser tab. However, most websites start giving the same warning (YouTube, vimeo, atlassian, reddit), so it would seem a lot of infrastructure is still using the deprecated default SameSite behavior. Given that the SDK never uses cookies, there is probably some other service (maybe a third party), that creates them, which will hopefully be fixed. I will forward to someone closer to the website.

**Comment by haved** [comment]
I enabled the future behaviour in chrome (see [here](https://www.chromium.org/updates/same-site/faq)), and everything still seemed to work.
