### ISSUE TITLE
Use granular imports from lodash

### ISSUE THREAD

**Issue by maksnester** [cognitedata/cognite-sdk-js#426]
You guys doing it again

> import { cloneDeepWith } from 'lodash';

Please use 

> import cloneDeepWith from 'lodash/cloneDeepWith';

Discussed in https://github.com/cognitedata/cognite-sdk-js/pull/386

**Comment by polomani** [comment]
@maksnester I would appreciate if you can add an eslint rule for this.
jssdk doesn't currenlty have people to take care of it
