### ISSUE TITLE
Issue with retry-axios on kubernetes pod (cannot read raxConfig of undefined)

### ISSUE THREAD

**Issue by alexchan150** [cognitedata/cognite-sdk-js#57]
Encountered a very strange bug that only occurred once deployed on a kubernetes pod. Building the docker image and running that locally works fine.

Happened when making the `sdk.Events.search` call on the _opint-prober_ project, and using the following params: 
`{
dir: 'asc',
minLastUpdatedTime: Date.now() - 1000*60*30,
sort: 'startTime'
}`

This is the error message: **TypeError: Cannot read property 'raxConfig' of undefined at onError (/usr/src/app/node_modules/retry-axios/build/src/index.js:29:29) at <anonymous>**

This was not due to network issues, as we tried ssh into the pod and make a call to the api, and it returned a proper response. It is important to note that due to this error, the service immediately throws an error (usually within 1 or 2 ms).

Using node 8.15.0, sdk release 1.5.1.

**Comment by ghost** [comment]
Closing it since we have a new implementation of retries
