### ISSUE TITLE
Support request cancellation

### ISSUE THREAD

**Issue by evancharlton** [cognitedata/cognite-sdk-js#69]
I know that canceling promises gets weird with JS, but it would be great to have a `.cancel()` method on requests that would at least ensure that the promise never gets resolved or rejected (or something? I don't know what consequences this would have).

The flow I'm trying to enable is something like:
```js
const MyComponent = ({ assetId }) => {
  const [asset, setAsset] = useState(null);
  useEffect(() => {
    const promise = sdk.Assets.retrieve(assetId).then(setAsset);
    // If this is unmounted while inflight, don't update an unmounted component.
    return () => promise.cancel();
  }, [assetId]);

  if (!asset) {
    return <Spinner />;
  }

  return <AssetRenderer asset={asset} />
};
```

**Comment by polomani** [comment]
@evancharlton  There are a lot of discussions about promise cancelation and it seems that it's not coming to JS. At least yet.
I've googled through proposed solutions through the internet (like here https://blog.bloomca.me/2017/12/04/how-to-cancel-your-promise.html) and I personally don't like much any of them. (bluebird doesn't work with `async/await`, wrappers seem to be something that's better to make in frontend instead, only in the places it's needed)

Do you guys use `Observables` and subscriptions? We might look in that way, as they are cancellable

**Comment by ghost** [comment]
We can also use this one: https://github.com/axios/axios#cancellation

**Comment by evancharlton** [comment]
Just to clarify: I'm not trying to actually cancel the request (because I know it's not coming to JS any time soon). However, I want to logically cancel it so that the then-chain is broken.

**Comment by evancharlton** [comment]
As an example, here's what we've been littering around when we remember to:
```js
const MyComponent = ({ assetId }) => {
  const [asset, setAsset] = useState(null);
  useEffect(() => {
    let canceled = false;
    const promise = sdk.Assets.retrieve(assetId).then(res => {
        if (!canceled) {
            setAsset(res);
        }
    });
    // If this is unmounted while inflight, don't update an unmounted component.
    return () => { canceled = true; }
  }, [assetId]);

  if (!asset) {
    return <Spinner />;
  }

  return <AssetRenderer asset={asset} />
};
```

**Comment by polomani** [comment]
Moved to Jira https://cognitedata.atlassian.net/browse/DEVX-9?atlOrigin=eyJpIjoiN2QyMDQwMDgwYzVlNDEzMmI2ZDY1NGY5Yzk2MjE5NjgiLCJwIjoiaiJ9
