### ISSUE TITLE
Dataframe functionality in SDK - API v1 

### ISSUE THREAD

**Issue by maciejmrowiec** [cognitedata/cognite-sdk-js#82]
API v1 is removing dataframe endpoints for retrieving datapoints due to it's tight overlap with datapoint retrieval. Main difference was in how the output was formatted.

Introduce equivalent functionality purely on SDK side based on retrieve datapoints endpoint. 

Targeted behaviour: https://doc.cognitedata.com/api/0.5/#operation/getDatapointsFrame
Underlying data source: https://doc.cognitedata.com/api/v1/#operation/getMultiTimeSeriesDatapoints

Intended for SDK 1.0

**Comment by maciejmrowiec** [comment]
FYI @larshagencognite ticket for dataframe in SDK

**Comment by maciejmrowiec** [comment]
@evancharlton @valerii-cognite if this is something you depend on ?

**Comment by valgussev** [comment]
From the migration guide it is removed https://github.com/cognitedata/cognitesdk-js/blob/v1/guides/MIGRATION_GUIDE_1xx_2xx.md, is there any relevant one we should use instead?

**Comment by ghost** [comment]
What do you need it for @valerii-cognite?

**Comment by valgussev** [comment]
https://github.com/cognitedata/operational-intelligence/blob/12c59e7f1a20a015aaa310cbc835bec39beaf0d2/src/components/DownloadChartModal/DownloadChartModal.js#L86
@evancharlton fyi

**Comment by ghost** [comment]
Thank you. So this is only needed to be able to convert datapoints to csv?
Do we think this should be natively supported by the SDK or convert to CSV on the fly?

**Comment by polomani** [comment]
Moved to Jira https://cognitedata.atlassian.net/browse/DEVX-15?atlOrigin=eyJpIjoiMTI3ZDhkZGVhYjQ5NDdiZThiODJlNzZlOTBkNWI5YzAiLCJwIjoiaiJ9
